// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpQuH2mevvtdw98MNUE0X1DdmvtSDeBSs',
    appId: '1:1012062066863:web:086912bc528bb374d49c5a',
    messagingSenderId: '1012062066863',
    projectId: 'misaludactiva-21760',
    authDomain: 'misaludactiva-21760.firebaseapp.com',
    storageBucket: 'misaludactiva-21760.firebasestorage.app',
    measurementId: 'G-T0K1GRBB6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdvzKB_ipxE1nta4PynESXeFu1wrMm5Tc',
    appId: '1:1012062066863:android:23ea3447067e3b44d49c5a',
    messagingSenderId: '1012062066863',
    projectId: 'misaludactiva-21760',
    storageBucket: 'misaludactiva-21760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqhhOStxmOHobN8Z6kOTzTIUcWSo0CfD4',
    appId: '1:1012062066863:ios:34f0a1e8e795e434d49c5a',
    messagingSenderId: '1012062066863',
    projectId: 'misaludactiva-21760',
    storageBucket: 'misaludactiva-21760.firebasestorage.app',
    androidClientId: '1012062066863-ohb4fm70nqvnb4au3nsjhk2tguq44ohe.apps.googleusercontent.com',
    iosClientId: '1012062066863-uak8s1ldame434ip6sa1o01c3liu8soq.apps.googleusercontent.com',
    iosBundleId: 'com.example.msa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqhhOStxmOHobN8Z6kOTzTIUcWSo0CfD4',
    appId: '1:1012062066863:ios:34f0a1e8e795e434d49c5a',
    messagingSenderId: '1012062066863',
    projectId: 'misaludactiva-21760',
    storageBucket: 'misaludactiva-21760.firebasestorage.app',
    androidClientId: '1012062066863-ohb4fm70nqvnb4au3nsjhk2tguq44ohe.apps.googleusercontent.com',
    iosClientId: '1012062066863-uak8s1ldame434ip6sa1o01c3liu8soq.apps.googleusercontent.com',
    iosBundleId: 'com.example.msa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpQuH2mevvtdw98MNUE0X1DdmvtSDeBSs',
    appId: '1:1012062066863:web:a0509d19e1c7237ed49c5a',
    messagingSenderId: '1012062066863',
    projectId: 'misaludactiva-21760',
    authDomain: 'misaludactiva-21760.firebaseapp.com',
    storageBucket: 'misaludactiva-21760.firebasestorage.app',
    measurementId: 'G-20QBMKV0NR',
  );

}